# Python Development Tools

So you want to develop programs and applications in Python?

You'll need to familiarize yourself with a Python development environment. One of the hardest parts of computer programming can be installing the language, and getting up and running with the development tools. But we will help guide you through the process, and recommend using tools that offer a low learning curve for beginners.

## Notebooks vs Local Development

Python notebooks (.IPYNB) documents provide an easy and intuitive learning experience for beginners. They have code "cells" we can "play" to see the results and learn along the way. Notebooks are also a popular choice among data science and machine learning practitioners, especially for quick prototypes, and rapid development.

Local development environments are used primarily for software development purposes, and for larger-scale applications. The local development environment involves command-line programming tools that can be tricky to install and configure.

In this book, we will conduct all exercises using [Google Colab Notebooks](./google-colab/overview.qmd), which are a type of Python Notebook document that can be executed in the cloud and managed via Google Drive. Google Drive makes it easy to copy and share the documents, and provides a familiar experience for beginners.
