# Installing Packages with Pip

Some packages are pre-installed, but we may need to install some ourselves.

Python has a rich ecosystem of packages (open source libraries authored by developers). When a developer wants to publish their package, they upload it to a centralized repository called the PyPI.


## Listing Installed Package

We use a `pip list` command to list all packages installed in the current environment (which in this case is the Google Colab environment).

In Google Colab, we prefix shell commands like `pip` commands with an exclaimation point, to differentiate them from python code.

```sh
!pip list
```

If you are looking for a specific package (like `pandas`), you can search for it within the displayed output:

```sh
!pip list | grep pandas
```



## Installing Packages


When we install packages, they get downloaded from the PyPI. Finally we can add optionally leverage a "capture magic" to suppress outputs during the installation process:


```sh
%%capture
!pip install yahooquery
```
