project:
  type: website # book
  output-dir: _build
  preview:
    port: 3456 # use the same port instead of a new one each time
    browser: true

jupyter: python3
execute:
  cache: true # re-render only when source changes

# https://quarto.org/docs/reference/projects/websites.html#section
website:
  title: "Python for Finance"
  site-url: https://prof-rossetti.github.io/python-for-finance/
  repo-url: https://github.com/prof-rossetti/python-for-finance
  repo-branch: main
  repo-actions: [edit, issue, source]
  #downloads: ["pdf", "epub", "docx"]
  #sharing: ["facebook", "twitter", "linkedin"]
  #code-links:
  search: true
  reader-mode: false
  page-navigation: true
  back-to-top-navigation: false
  bread-crumbs: true

  # https://quarto.org/docs/reference/projects/websites.html#navbar
  navbar:
    right:
      - about-author.qmd

  # https://quarto.org/docs/reference/projects/websites.html#sidebar
  # NOTE: all sections need href, or else their links don't appear properly in the left sidebar!  https://github.com/quarto-dev/quarto-cli/issues/10102
  sidebar:
    contents:
      - section:
        href: index.qmd
      - section:
        href: why-python.qmd

      #- "---------"
      - section:
        href: notes/dev-tools/index.qmd
        contents:
          - section:
            href: notes/dev-tools/google-colab/overview.qmd
            contents:
              - section:
                href: notes/dev-tools/google-colab/form-inputs.qmd
              - section:
                href: notes/dev-tools/google-colab/notebook-secrets.qmd
              - section:
                href: notes/dev-tools/google-colab/integrations.qmd
          - section:
            href: notes/dev-tools/pip.qmd

      - "---------"
      - section:
        href: courses/fin-apps.qmd
        text: "I. Intro to Financial Applications" # "I. Financial Applications" # "I. Intro to Financial Applications"
        contents:
          - section:
            href: notes/python-lang.qmd

          - section:
            href: notes/basic-datatypes/index.qmd
            contents:
              - section:
                href: notes/basic-datatypes/numbers.qmd
              - section:
                href: notes/basic-datatypes/strings.qmd
              - section:
                href: notes/basic-datatypes/booleans.qmd

          - section:
            href: notes/python-operators.qmd

          - section:
            href: notes/control-flow/index.qmd
            contents:
              - section:
                href: notes/control-flow/conditional-logic.qmd
              - section:
                href: notes//control-flow/custom-functions.qmd
                contents:
                - section:
                  href: notes/control-flow/function-docs.qmd
                - section:
                  href: notes/control-flow/unit-testing.qmd
                - section:
                  href: notes/control-flow/errors.qmd

          - section:
            href: notes/container-datatypes/index.qmd
            contents:
              - section:
                href: notes/container-datatypes/lists.qmd
              - section:
                href: notes/container-datatypes/dictionaries.qmd

          - section:
            href: notes/python-modules/index.qmd
            contents:
              - section:
                href: notes/python-modules/datetime.qmd
              - section:
                href: notes/python-modules/random.qmd
              - section:
                href: notes/python-modules/statistics.qmd








      - "---------"
      - section:
        href: courses/applied-ds.qmd
        text: "II. Applied Data Science" #"II. Applied Data Science for Finance in Python" #"II. Applied Data Science"
        #contents:
        #  - applied-ds/unit2.qmd

      - "---------"
      - section:
        href: courses/fin-modeling.qmd
        text: "III. Advanced Financial Modeling" # "III. Advanced Financial Modeling in Python" # "III. Financial Modeling" #"III. Advanced Financial Modeling"
        #contents:
        #  - applied-ds/unit2.qmd

      - "---------"
      - about-author.qmd


format:
  # https://quarto.org/docs/reference/formats/html.html#table-of-contents
  html:
    theme: cosmo
    code-copy: true
    code-fold: false #show
    toc: true
    #toc-location: left
    #number-sections: false
    #number-depth: 1

  #pdf:
  #  documentclass: scrreprt
