project:
  type: book
  output-dir: _build
  preview:
    port: 3456 # use the same port instead of a new one each time
    browser: true

# https://quarto.org/docs/reference/projects/books.html#section
book:
  title: "Python for Finance"
  subtitle: "2024 Edition"
  author: "Michael Rossetti"
  #date: "2024-06-22"
  #date-format
  #abstract: "..."
  #description: "..."
  edition: "2024"
  #doi: "...."
  #isbn: ""
  #issn: ""
  #citation-key: ""
  #keyword: "..."
  #language: "en"
  #license: ""

  #url: ""
  #favicon: ""
  #cover-image: "....png"
  #image: "...png"

  #google-analytics: "X-----"
  #open-graph:

  site-url: https://s2t2.github.io/quarto-python-autodoc-template/
  repo-url: https://github.com/s2t2/quarto-python-autodoc-template
  repo-branch: main
  repo-actions: [edit, issue, source]
  #downloads: ["pdf", "epub", "docx"]
  #sharing: ["facebook", "twitter", "linkedin"]
  #code-links:
  search: true
  reader-mode: false
  page-navigation: true
  back-to-top-navigation: false
  bread-crumbs: true

  # body-header:
  # body-footer:

  # https://quarto.org/docs/reference/projects/books.html#navbar
  # navbar:

  # https://quarto.org/docs/reference/projects/books.html#sidebar
  # sidebar:

  # https://quarto.org/docs/books/book-structure.html#parts-appendices
  chapters:
    - index.qmd
    #- preface.qmd
    #- onboarding.qmd

    - "---------"
    - part: dev-tools/index.qmd
      title: "0 - Python Development Tools"
      chapters:
        - dev-tools/google-colab/overview.qmd
        - dev-tools/google-colab/settings.qmd

    - "---------"
    - part: fin-apps/index.qmd
      title: "I. Intro to Financial Applications"
      #chapters:
      #  - fin-apps/unit2.qmd

    - "---------"
    - part: applied-ds/index.qmd
      title: "II. Applied Data Science"
      #chapters:
      #  - applied-ds/unit2.qmd

    - "---------"
    - part: fin-modeling/index.qmd
      title: "III. Advanced Financial Modeling"
      #chapters:
      #  - applied-ds/unit2.qmd

    - "---------"
    - meet-professor.qmd

    #- references.qmd

#bibliography: references.bib

format:
  # https://quarto.org/docs/reference/formats/html.html#table-of-contents
  html:
    theme: cosmo
    code-copy: true
    #toc: true
    #toc-location: left
    #number-sections: true
    #number-depth: 3

  #pdf:
  #  documentclass: scrreprt
