project:
  type: website # book
  output-dir: _build
  preview:
    port: 3456 # use the same port instead of a new one each time
    browser: true


# https://quarto.org/docs/reference/projects/websites.html#section
website:
  title: "Python for Finance"
  site-url: https://prof-rossetti.github.io/python-for-finance/
  repo-url: https://github.com/prof-rossetti/python-for-finance
  repo-branch: main
  repo-actions: [edit, issue, source]
  #downloads: ["pdf", "epub", "docx"]
  #sharing: ["facebook", "twitter", "linkedin"]
  #code-links:
  search: true
  reader-mode: false
  page-navigation: true
  back-to-top-navigation: false
  bread-crumbs: true

  # https://quarto.org/docs/reference/projects/websites.html#navbar
  navbar:
    right:
      - about-author.qmd

  # https://quarto.org/docs/reference/projects/websites.html#sidebar
  sidebar:
    contents:
      - index.qmd
      - why-python.qmd
      #- preface.qmd
      #- onboarding.qmd

      #- "---------"
      - section: notes/dev-tools/index.qmd
        contents:
          - section: notes/dev-tools/google-colab/overview.qmd
            contents:
              - section: notes/dev-tools/google-colab/form-inputs.qmd
              - section: notes/dev-tools/google-colab/notebook-secrets.qmd
              - section: notes/dev-tools/google-colab/integrations.qmd
          - section: notes/dev-tools/pip.qmd

      - "---------"
      - section: courses/fin-apps.qmd
        text: "I. Financial Applications" # "I. Intro to Financial Applications"
        contents:
          - section: notes/python-lang.qmd

          - section: notes/basic-datatypes/index.qmd
            contents:
              - notes/basic-datatypes/numbers.qmd
              - notes/basic-datatypes/strings.qmd
              - notes/basic-datatypes/booleans.qmd

          - section: notes/python-operators.qmd

          - section: notes/control-flow/index.qmd
            contents:
              - notes/control-flow/conditional-logic.qmd
              - section: notes//control-flow/custom-functions.qmd
                contents:
                - notes/control-flow/function-docs.qmd
                - notes/control-flow/unit-testing.qmd

          - section: notes/container-datatypes/index.qmd
            contents:
              - notes/container-datatypes/lists.qmd
              - notes/container-datatypes/dictionaries.qmd

          - section: notes/python-modules/index.qmd
            contents:
              - notes/python-modules/datetime.qmd
              - notes/python-modules/random.qmd
              - notes/python-modules/statistics.qmd








      - "---------"
      - section: courses/applied-ds.qmd
        text: "II. Applied Data Science"
        #chapters:
        #  - applied-ds/unit2.qmd

      - "---------"
      - section: courses/fin-modeling.qmd
        text: "III. Financial Modeling" #"III. Advanced Financial Modeling"
        #chapters:
        #  - applied-ds/unit2.qmd

      - "---------"
      - about-author.qmd


format:
  # https://quarto.org/docs/reference/formats/html.html#table-of-contents
  html:
    theme: cosmo
    code-copy: true
    #toc: true
    #toc-location: left
    #number-sections: false
    #number-depth: 1

  #pdf:
  #  documentclass: scrreprt
