project:
  type: website # book
  output-dir: _build
  preview:
    port: 3456 # use the same port instead of a new one each time
    browser: true

#jupyter: python3
#execute:
#  #cache: true # re-render only when source changes
# # eval: false

# https://quarto.org/docs/reference/projects/websites.html#section
website:
  title: "Python for Finance"
  site-url: https://prof-rossetti.github.io/python-for-finance/
  repo-url: https://github.com/prof-rossetti/python-for-finance
  repo-branch: main
  repo-actions: [edit, issue, source]
  #downloads: ["pdf", "epub", "docx"]
  #sharing: ["facebook", "twitter", "linkedin"]
  #code-links:
  search: true
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: false
  bread-crumbs: true

  # https://quarto.org/docs/reference/projects/websites.html#navbar
  navbar:
    right:
      - about-author.qmd

  # https://quarto.org/docs/reference/projects/websites.html#sidebar
  # NOTE: all sections need href, or else their links don't appear properly in the left sidebar!  https://github.com/quarto-dev/quarto-cli/issues/10102
  sidebar:
    contents:
      - section:
        href: index.qmd
      - section:
        href: why-python.qmd

      #- "---------"
      - section:
        href: notes/dev-tools/index.qmd
        text: "Python Development Tools"
        contents:
          - section:
            href: notes/dev-tools/google-colab/overview.qmd
            #contents:
            #  - section:
            #    href: notes/dev-tools/google-colab/table-of-contents.qmd
            #    text: "Table of Contents"
            #  - section:
            #    href: notes/dev-tools/google-colab/filesystem.ipynb
            #    text: "Accessing the Filesystem"
            #  - section:
            #    href: notes/dev-tools/google-colab/form-inputs.ipynb
            #    text: "Forms and Inputs"
            #  - section:
            #    href: notes/dev-tools/google-colab/notebook-secrets.qmd
            #    text: "Notebook Secrets"
            #  - section:
            #    href: notes/dev-tools/google-colab/advanced-integrations.ipynb
            #    text: "Advanced Integrations"
          - section:
            href: notes/dev-tools/pip.ipynb
            text: "Installing Packages with Pip"

      #- "---------"
      - section:
        href: courses/fin-apps.qmd
        text: "I. Financial Applications" # "I. Financial Applications" # "I. Intro to Financial Applications"
        contents:
          #
          # PYTHON LANGUAGE OVERVIEW
          #
          - section:
            href: notes/python-lang/overview.ipynb
            text: "Python Language Overview"
            contents:

              - section:
                href: notes/python-lang/basic-datatypes/index.qmd
                text: "Basic Datatypes"
                contents:
                  # basic datatypes here:
                  - section:
                    href: notes/python-lang/basic-datatypes/booleans.qmd
                  - section:
                    href: notes/python-lang/basic-datatypes/numbers.qmd
                  - section:
                    href: notes/python-lang/basic-datatypes/strings.qmd
                  # container datatypes here:
                  #- section:
                  #  href: notes/python-lang/container-datatypes/lists.qmd
                  #- section:
                  #  href: notes/python-lang/container-datatypes/dictionaries.qmd

              - section:
                href: notes/python-lang/python-operators.qmd

              - section:
                href: notes/python-lang/control-flow/index.qmd
                contents:
                  - section:
                    href: notes/python-lang/control-flow/conditional-logic.qmd
                  - section:
                    href: notes/python-lang/control-flow/custom-functions.qmd
                    #contents:
                    #- section:
                    #  href: notes/python-lang/control-flow/function-docs.qmd
                    #- section:
                    #  href: notes/python-lang/control-flow/unit-testing.qmd
                  #- section:
                  #  href: notes/python-lang/control-flow/errors.qmd
                  - section:
                    href: notes/python-lang/control-flow/while-loops.qmd
                    #text: "While Loops, Counters, and Accumulators"

              - section:
                #href: notes/python-lang/container-datatypes/index.qmd
                text: "Container Datatypes"
                contents:
                  - section:
                    href: notes/python-lang/container-datatypes/lists.qmd
                  - section:
                    href: notes/python-lang/container-datatypes/dictionaries.qmd

              #- section:
              #  href: notes/python-modules/index.qmd
              #  text: "Python Modules"
              #  contents:
              #    - section:
              #      href: notes/python-modules/datetime.qmd
              #    - section:
              #      href: notes/python-modules/random.qmd
              #    - section:
              #      href: notes/python-modules/statistics.qmd

          #
          # DATA PROCESSING
          #
          - section:
            href: notes/data-processing/index.qmd
            text: "Data Processing"
            contents:
              #- section:
              #  href: notes/data-processing/looping.qmd
              #  text: "List Iteration and Looping"
              - section:
                href: notes/data-processing/sorting.qmd
                text: "Sorting Lists"
              - section:
                href: notes/data-processing/mapping.qmd
                text: "Mapping Lists"
              - section:
                href: notes/data-processing/filtering.qmd
                text: "Filtering Lists"
              - section:
                href: notes/data-processing/list-comprehensions.qmd
                text: "List Comprehensions"

          #
          # DATAVIZ
          #
          - section:
            href: notes/dataviz/overview.qmd
            text: "Data Visualization"
            contents:
              - section:
                href: notes/dataviz/trendlines.qmd
                text: "Charts with Trendlines"
              - section:
                href: notes/dataviz/candlestick-charts.qmd
                text: "Candlestick Charts"
          #
          # FETCHING DATA FROM THE INTERNET
          #
          - section:
            href: notes/fetching-data/overview.qmd
            text: "Fetching Data from the Internet"
            #contents:
            #  - section:
            #    href: notes/data-processing/sorting.qmd
            #    text: "Sorting Lists"








      - "---------"
      - section:
        href: courses/applied-ds.qmd
        text: "II. Applied Data Science" #"II. Applied Data Science for Finance in Python" #"II. Applied Data Science"
        #contents:
        #  - applied-ds/unit2.qmd

      - "---------"
      - section:
        href: courses/fin-modeling.qmd
        text: "III. Financial Modeling" # "III. Advanced Financial Modeling in Python" # "III. Financial Modeling" #"III. Advanced Financial Modeling"
        #contents:
        #  - applied-ds/unit2.qmd

      #- "---------"
      #- about-author.qmd

      #
      # APPENDICES ???
      #
      - "---------"
      - text: "Appendices"
      #- "---------"
      - section:
        text: "A. Google Colab Extras" # In Depth
        contents:
          - section:
            href: notes/dev-tools/google-colab/table-of-contents.qmd
            text: "Table of Contents"
          - section:
            href: notes/dev-tools/google-colab/filesystem.ipynb
            text: "Accessing the Filesystem"
          - section:
            href: notes/dev-tools/google-colab/form-inputs.ipynb
            text: "Forms and Inputs"
          - section:
            href: notes/dev-tools/google-colab/notebook-secrets.qmd
            text: "Notebook Secrets"
          - section:
            href: notes/dev-tools/google-colab/advanced-integrations.ipynb
            text: "Advanced Integrations"
      - "---------"
      - section:
        text: "B. Function Documentation and Testing" # In Depth
        contents:
          - section:
            href: notes/python-lang/control-flow/function-docs.qmd
          - section:
            href: notes/python-lang/control-flow/unit-testing.qmd
      - "---------"
      - section:
        text: "C. Handling and Raising Errors"
        href: notes/python-lang/control-flow/errors.qmd
      - "---------"
      - section:
        href: notes/python-modules/index.qmd
        text: "D. Python Modules Overview"
        contents:
          - section:
            href: notes/python-modules/datetime.qmd
          - section:
            href: notes/python-modules/random.qmd
          - section:
            href: notes/python-modules/statistics.qmd

format:
  # https://quarto.org/docs/reference/formats/html.html#table-of-contents
  html:
    # https://bootswatch.com/
    #
    theme: pulse #cosmo
      #light: pulse
      #dark: superhero
    code-copy: true
    code-fold: false #show
    #code-line-numbers: true
    toc: true
    #toc-location: left
    #number-sections: false
    #number-depth: 1

  #pdf:
  #  documentclass: scrreprt
