project:
  type: website # book
  output-dir: _build
  preview:
    port: 3456 # use the same port instead of a new one each time
    browser: true

#jupyter: python3
#execute:
#  #cache: true # re-render only when source changes
# # eval: false

# https://quarto.org/docs/reference/projects/websites.html#section
website:
  title: "Python for Finance"
  site-url: https://prof-rossetti.github.io/python-for-finance/
  repo-url: https://github.com/prof-rossetti/python-for-finance
  repo-branch: main
  repo-actions: [edit, issue, source]
  repo-subdir: docs
  #downloads: ["pdf", "epub", "docx"]
  #sharing: ["facebook", "twitter", "linkedin"]
  #code-links:
  search: true
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: false
  bread-crumbs: true

  # https://quarto.org/docs/reference/projects/websites.html#navbar
  navbar:
    right:
      - about-author.qmd

  # https://quarto.org/docs/reference/projects/websites.html#sidebar
  # NOTE: all sections need href, or else their links don't appear properly in the left sidebar!  https://github.com/quarto-dev/quarto-cli/issues/10102
  sidebar:
    contents:
      - section:
        href: index.qmd
      - section:
        href: why-python.qmd

      - "---------"
      - section:
        href: notes/dev-tools/index.qmd
        text: "Python Development Tools"
        contents:
          - section:
            href: notes/dev-tools/google-colab/overview.qmd
            contents:
              - section:
                href: notes/dev-tools/google-colab/table-of-contents.qmd
                text: "Table of Contents"
              - section:
                href: notes/dev-tools/google-colab/filesystem.ipynb
                text: "Accessing the Filesystem"
              - section:
                href: notes/dev-tools/google-colab/form-inputs.ipynb
                text: "Forms and Inputs"
              - section:
                href: notes/dev-tools/google-colab/notebook-secrets.qmd
                text: "Notebook Secrets"
              - section:
                href: notes/dev-tools/google-colab/advanced-integrations.ipynb
                text: "Advanced Integrations"
          - section:
            href: notes/dev-tools/pip.ipynb
            text: "Installing Packages with Pip"

      - "---------"
      - section:
        href: courses/fin-apps.qmd
        text: "I. Financial Applications" # "I. Financial Applications" # "I. Intro to Financial Applications"
        contents:
          #
          # PYTHON LANGUAGE OVERVIEW
          #
          - section:
            href: notes/python-lang/overview.ipynb
            text: "Python Language Overview"
            contents:

              - section:
                href: notes/python-lang/basic-datatypes/index.qmd
                text: "Basic Datatypes"
                contents:
                  # basic datatypes here:
                  - section:
                    href: notes/python-lang/basic-datatypes/booleans.qmd
                  - section:
                    href: notes/python-lang/basic-datatypes/numbers.qmd
                  - section:
                    href: notes/python-lang/basic-datatypes/strings.qmd

              - section:
                href: notes/python-lang/python-operators.qmd

              - section:
                href: notes/python-lang/control-flow/index.qmd
                contents:
                  - section:
                    href: notes/python-lang/control-flow/conditional-logic.qmd
                  - section:
                    href: notes/python-lang/control-flow/custom-functions.qmd
                    #contents:
                    #- section:
                    #  href: notes/python-lang/control-flow/function-docs.qmd
                    #- section:
                    #  href: notes/python-lang/control-flow/unit-testing.qmd
                  #- section:
                  #  href: notes/python-lang/control-flow/errors.qmd
                  - section:
                    href: notes/python-lang/control-flow/while-loops.qmd

              - section:
                href: notes/python-lang/container-datatypes/index.qmd
                text: "Container Datatypes"
                contents:
                  - section:
                    href: notes/python-lang/container-datatypes/lists.qmd
                  - section:
                    href: notes/python-lang/container-datatypes/dictionaries.qmd

              - section:
                href: notes/python-modules/index.qmd
                text: "Python Modules"
                contents:
                  - section:
                    href: notes/python-modules/math.qmd
                  - section:
                    href: notes/python-modules/random.qmd
                  - section:
                    href: notes/python-modules/statistics.qmd
                  - section:
                    href: notes/python-modules/datetime.qmd

          #
          # DATA PROCESSING
          #
          - section:
            href: notes/data-processing/index.qmd
            text: "Data Processing"
            contents:
              - section:
                href: notes/data-processing/for-loops.qmd
                text: "List Iteration and Looping"
              - section:
                href: notes/data-processing/sorting.qmd
                text: "Sorting Lists"
              - section:
                href: notes/data-processing/mapping.qmd
                text: "Mapping Lists"
              - section:
                href: notes/data-processing/filtering.qmd
                text: "Filtering Lists"
              - section:
                href: notes/data-processing/list-comprehensions.qmd
                text: "List Comprehensions"

          #
          # DATAVIZ
          #
          - section:
            href: notes/dataviz/overview.qmd
            text: "Data Visualization"
            contents:
              - section:
                href: notes/dataviz/trendlines.qmd
                text: "Charts with Trendlines"
              - section:
                href: notes/dataviz/candlestick-charts.qmd
                text: "Candlestick Charts"
          #
          # FETCHING DATA FROM THE INTERNET
          #
          - section:
            href: notes/fetching-data/overview.qmd
            text: "Fetching Data from the Internet"
            contents:
              - section:
                href: notes/fetching-data/json-data.qmd
              - section:
                href: notes/fetching-data/csv-data.qmd
              - section:
                href: notes/fetching-data/xml.qmd
              - section:
                href: notes/fetching-data/html-web-scraping.qmd
                #text: "HTML Data (Web Scraping)"
              #- section:
              #  href: notes/fetching-data/apis.qmd
              #  text: "APIs"







      - "---------"
      - section:
        href: courses/applied-ds.qmd
        text: "II. Applied Data Science" #"II. Applied Data Science for Finance in Python" #"II. Applied Data Science"
        contents:
          #
          # PANDAS PACKAGE OVERVIEW
          #
          - section:
            href: notes/pandas/overview.qmd
            text: "Pandas Package Overview"
            contents:
              - section:
                href: notes/pandas/dataframes-2.ipynb
                text: "Dataframes"
              #- section:
              #  href: notes/pandas/dataframes.qmd
              #  text: "Dataframes"

              - section:
                href: notes/pandas/grouping-pivoting.qmd
                text: "Grouping and Pivoting"
              - section:
                href: notes/pandas/shift-methods.qmd
                text: "Shift based Methods" # "Growth and Cumulative Growth"
              - section:
                href: notes/pandas/moving-averages.qmd
                text: "Moving Averages"
              - section:
                href: notes/pandas/joining-merging.ipynb
                text: "Joining and Merging"

          - section:
            href: notes/applied-stats/overview.qmd
            text: "Applied Statistics"
            contents:
              #- section:
              #  href: notes/applied-stats/basic-tests.ipynb
              #  text: "Statistical Tests"
              - section:
                href: notes/applied-stats/summary-stats.qmd
                text: "Summary Statistics"
              - section:
                href: notes/applied-stats/basic-tests.qmd
                text: "Statistical Tests"
              - section:
                href: notes/applied-stats/data-scaling.qmd
                text: "Data Scaling"
              - section:
                href: notes/applied-stats/correlation.qmd
                text: "Correlation"



      - "---------"
      - section:
        href: courses/fin-modeling.qmd
        text: "III. Financial Modeling" # "III. Advanced Financial Modeling in Python" # "III. Financial Modeling" #"III. Advanced Financial Modeling"
        contents:

          - section:
            href: notes/predictive-modeling/index.qmd
            text: "Predictive Modeling"

          - section:
            href: notes/predictive-modeling/ml-foundations/index.qmd
            text: "Machine Learning Foundations"
            contents:

              - section:
                href: notes/predictive-modeling/ml-foundations/generalization.qmd
                text: "Generalization"
              - section:
                href: notes/predictive-modeling/ml-foundations/data-encoding.qmd
                text: "Data Encoding"
              - section:
                href: notes/applied-stats/data-scaling.qmd
                text: "Data Scaling"

          - "--------------"
          - section:
            href: notes/predictive-modeling/supervised-learning.qmd
            text: "Supervised Learning"
            contents:

              - section:
                href: notes/predictive-modeling/regression/index.qmd
                text: "Regression"
                contents:
                  - section:
                    href: notes/predictive-modeling/regression/linear.qmd
                    text: "Linear Regression w/ sklearn"
                  - section:
                    href: notes/predictive-modeling/regression/ols.qmd
                    text: "Linear Regression w/ statsmodels"
                  - section:
                    href: notes/predictive-modeling/regression/time-series-forecasting.qmd
                    text: "Time Series Forecasting"
                  - section:
                    href: notes/predictive-modeling/regression/seasonality.qmd
                    text: "Seasonality Analysis"

              - section:
                href: notes/predictive-modeling/regression/autoregressive-models.qmd
                text: "Autoregressive Models"

              - section:
                href: notes/predictive-modeling/classification/index.qmd
                text: "Classification"
                contents:
                  - section:
                    href: notes/predictive-modeling/classification/binary.qmd
                    text: "Binary Classification"
                  - section:
                    href: notes/predictive-modeling/classification/multiclass.qmd
                    text: "Multi-class Classification"

          - "--------------"
          - section:
            href: notes/predictive-modeling/model-management/index.qmd
            text: "Model Management"
            contents:
              - section:
                href: notes/predictive-modeling/model-management/saving-loading.qmd
                text: "Model Management"
              - section:
                href: notes/predictive-modeling/model-management/deploying.qmd
                text: "Model Deployment"
              - section:
                href: notes/predictive-modeling/model-optimization/grid-search.qmd
                text: "Model Optimization"

          - "--------------"
          - section:
            href: notes/predictive-modeling/unsupervised-learning.qmd
            text: "Unsupervised Learning"
            contents:

              - section:
                href: notes/predictive-modeling/dimensionality-reduction/pca.qmd
                text: "Dimensionality Reduction"

              - section:
                href: notes/predictive-modeling/clustering/index.qmd
                text: "Clustering"


      #- "---------"
      #- about-author.qmd

      #
      # APPENDICES ???
      #
      - "---------"
      - text: "Appendices"
      #- "---------"
      - section:
        text: "Financial Data Sources"
        contents:
          - section:
            href: notes/financial-data-sources/pandas-datareader.qmd
            text: "Pandas Datareader"


format:
  # https://quarto.org/docs/reference/formats/html.html#table-of-contents
  html:
    # https://bootswatch.com/
    #
    theme: pulse #cosmo
      #light: pulse
      #dark: superhero
    code-copy: true
    code-fold: false #show
    #code-line-numbers: true
    code-overflow: wrap # wrap code when it overflows the page
    toc: true
    toc-depth: 4 # specify the number of section levels to include in the table of contents
    #toc-expand: 3 # specify how much of the table of contents to show initially (defaults to 1 with auto-expansion as the user scrolls)
    toc-expand: true # show all levels by default (not just on expansion)
    #toc-location: left
    #number-sections: false
    #number-depth: 1

  #pdf:
  #  documentclass: scrreprt
